name: weatherapp
description: A new Flutter application.

publish_to: 'everyone'
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  location: ^3.0.0
  http: ^0.12.1
  flutter_spinkit: "^4.1.2"
  weather_icons: 2.0.1
  fluttertoast: ^4.0.0
  flutter_sparkline: ^0.1.0
  intl: ^0.16.0
  fl_chart: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900

    - family: PatuaOne
      fonts:
        - asset: fonts/PatuaOne-Regular.ttf
          weight: 400